version: '3'

services:

  postgres:
    image: library/postgres:9.5-alpine
    environment:
      POSTGRES_USER: wazimap_np
      POSTGRES_PASSWORD: wazimap_np
      POSTGRES_DB: wazimap_np

  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    restart: always
    command: wait-for-it postgres-host:5432 --strict --timeout=30 -- start-web
    depends_on:
      - postgres
    links:
      - postgres:postgres-host
    volumes:
      - ./:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - HOST_USER_ID
      - HOST_GROUP_ID
      - APP_ENV
      - POSTGRES_HOST=postgres-host
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=wazimap_np
      - POSTGRES_PASSWORD=wazimap_np
      - POSTGRES_DATABASE=wazimap_np

  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    restart: always
    entrypoint: wait-for-it web-host:8000 --strict --timeout=30 -- start-caddy
    depends_on:
      - web
    links:
      - web:web-host
    volumes:
      - ./compose/caddy/Caddyfile:/etc/Caddyfile
      - ./compose/common/bin/wait-for-it:/usr/local/sbin/wait-for-it
      - ./compose/caddy/bin/start-caddy:/usr/local/sbin/start-caddy
      - ./certs:/etc/caddycerts
      - ./static:/static
    environment:
      - CADDYPATH=/etc/caddycerts
      - PROXY_HOST=web-host
      - PROXY_PORT=8000
      - HOST_NAME=localhost # Change to nepalmap.org once ready to use in production
    ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:443:443"
        - "2015:2015"       # Remove this port mapping once ready to use in production
