version: '3'

services:

  postgres:
    image: library/postgres:9.5-alpine
    environment:
      POSTGRES_USER: wazimap_np
      POSTGRES_PASSWORD: wazimap_np
      POSTGRES_DB: wazimap_np

  web:
    build:
      context: .
      dockerfile: compose/web/Dockerfile
    restart: always
    command: wait-for-it postgres:5432 --strict --timeout=30 -- start-web
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    environment:
      - HOST_USER_ID
      - HOST_GROUP_ID
      - APP_ENV
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=wazimap_np
      - POSTGRES_PASSWORD=wazimap_np
      - POSTGRES_DATABASE=wazimap_np
