version: '3'

services:

  postgres:
    image: library/postgres:9.5-alpine
    environment:
      POSTGRES_USER: wazimap_np
      POSTGRES_PASSWORD: wazimap_np
      POSTGRES_DB: wazimap_np

  web:
    build:
      context: .
      dockerfile: ./compose/web/Dockerfile
    restart: always
    command: wait-for-it postgres:5432 --strict --timeout=30 -- start-web
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    environment:
      - HOST_USER_ID
      - HOST_GROUP_ID
      - APP_ENV
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=wazimap_np
      - POSTGRES_PASSWORD=wazimap_np
      - POSTGRES_DATABASE=wazimap_np

  caddy:
    build:
      context: .
      dockerfile: ./compose/caddy/Dockerfile
    restart: always
    entrypoint: wait-for-it web:8000 --strict --timeout=30 -- start-caddy
    depends_on:
      - web
    volumes:
      - ./compose/caddy/Caddyfile:/etc/Caddyfile
      - ./compose/common/bin/wait-for-it:/usr/local/sbin/wait-for-it
      - ./compose/caddy/bin/start-caddy:/usr/local/sbin/start-caddy
      - ./certs:/etc/caddycerts
      - ./static:/static
    environment:
      - APP_ENV
      - TLS_EMAIL
      - CADDYPATH=/etc/caddycerts
      - PROXY_HOST=web
      - PROXY_PORT=8000
      - HOST_NAME=staging.nepalmap.org # Change to staging server for nepalmap.org
    ports:
        - "0.0.0.0:80:80"
        - "0.0.0.0:443:443"
